[package]
name = "transamerica-hand-test"
version = "0.1.0"
authors = ["Scott McMurray <scottmcm@users.noreply.github.com>"]
edition = "2018"
license = "OSL-3.0"
publish = false

[dependencies]
itertools = "0.7"
fnv = "1.0"
rayon = "1.0"

[profile.release]
panic = "abort"
lto = true
